# Generated by Django 4.0.2 on 2022-02-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treeviewlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('section_id', models.CharField(max_length=100)),
                ('section_name', models.CharField(max_length=100)),
                ('workproduct', models.CharField(max_length=100)),
                ('wp_type', models.CharField(max_length=100)),
                ('wp_category', models.CharField(max_length=100)),
                ('wp_condition', models.CharField(max_length=100)),
            ],
        ),
    ]
